import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { createStore, compose } from 'redux';
import reducer from './reducers';
import App from './routes/App';
import './assets/styles/App.scss';

const initialState = {
  user: {},
  playing: {},
  myList: [],
  searchResult: [],
  trends: [
    {
      id: 2,
      slug: 'tvshow-8',
      title: 'Venom II',
      type: 'Action',
      language: 'English',
      year: 2012,
      contentRating: '16+',
      duration: 148,
      cover: 'https://lh3.googleusercontent.com/proxy/Juiq2J9F2U2PwuAmSfUtXJwHhpBUJ2GIn1s5e0sI7MtZcywZEMWGrfwoONmB83LQduSfONP5tyTwDC3cEhhdM_d_vZFfwLTGBATIGzdV7zw_Eu6rSWe8WN1gpjGE',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    },
    {
      id: 3,
      slug: 'tvshow-9',
      title: 'Eternals',
      type: 'Action',
      language: 'English',
      year: 2019,
      contentRating: '16+',
      duration: 128,
      cover: 'https://static.displate.com/280x392/displate/2021-10-05/69689327d8b72f488fdafc7c6fe5a469_c38f2afa07622b6ef36fb65915c80e7e.jpg',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    },
    {
      id: 4,
      slug: 'tvshow-10',
      title: 'Black widow',
      type: 'Animation',
      language: 'English',
      year: 2011,
      contentRating: '16+',
      duration: 346,
      cover: 'https://lh3.googleusercontent.com/proxy/8P0QgEAdz5n1S0RAl61SCDPxPPKVv25c6C-sRNUUiAn6TorUFughG5pY_Of7iT-3buZj87tyfJZgLGECYFRi2Ca3qzkiENwb1HkeF3yfSJMOH7bCcsboc5tYufIsAn_4b7iX1h6erHzHdn7RUHbQTxBZGtplsW8',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    },
    {
      id: 5,
      slug: 'tvshow-11',
      title: 'Avengers, end game',
      type: 'War',
      language: 'English',
      year: 2015,
      contentRating: '16+',
      duration: 226,
      cover: 'https://m.media-amazon.com/images/I/71niXI3lxlL._AC_SY741_.jpg',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    },
    {
      id: 6,
      slug: 'tvshow-12',
      title: 'Spider man',
      type: 'Comedy',
      language: 'English',
      year: 2018,
      contentRating: '16+',
      duration: 190,
      cover: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/spider-man-homecoming-1547733212.jpg?crop=1xw:1xh;center,top&resize=980:*',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    },
    {
      id: 7,
      slug: 'tvshow-13',
      title: 'Avengers',
      type: 'Drama',
      language: 'English',
      year: 2010,
      contentRating: '16+',
      duration: 160,
      cover: 'https://tomenotaaqp.files.wordpress.com/2012/05/los-vengadores-the-avengers.jpg',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    },
    {
      id: 8,
      slug: 'tvshow-8',
      title: 'Capitán américa, el primer vengador',
      type: 'Action',
      language: 'English',
      year: 2012,
      contentRating: '16+',
      duration: 148,
      cover: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/capita-n-ame-rica-el-primer-vengador-1525786476.jpg?crop=1xw:1xh;center,top&resize=980:*',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    },
    {
      id: 9,
      slug: 'tvshow-9',
      title: 'Ant man - wasp',
      type: 'Action',
      language: 'English',
      year: 2019,
      contentRating: '16+',
      duration: 128,
      cover: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/antman-avispa-1533032018.jpg?crop=1xw:1xh;center,top&resize=980:*',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    },
    {
      id: 10,
      slug: 'tvshow-10',
      title: 'Thor ragnarok',
      type: 'Animation',
      language: 'English',
      year: 2011,
      contentRating: '16+',
      duration: 346,
      cover: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/thor-ragnarok-1525788074.jpg?crop=1xw:1xh;center,top&resize=980:*',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    },
  ],
  originals: [
    {
      id: 11,
      slug: 'tvshow-11',
      title: 'Iron man 1',
      type: 'War',
      language: 'English',
      year: 2015,
      contentRating: '16+',
      duration: 226,
      cover: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/iron-man-1-1525786538.jpg?crop=1xw:1xh;center,top&resize=980:*',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    },
    {
      id: 12,
      slug: 'tvshow-12',
      title: 'Black panther',
      type: 'Comedy',
      language: 'English',
      year: 2018,
      contentRating: '16+',
      duration: 190,
      cover: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/black-panther-1525787938.jpg?crop=1xw:1xh;center,top&resize=980:*',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    },
    {
      id: 13,
      slug: 'tvshow-13',
      title: 'El increible HULK',
      type: 'Drama',
      language: 'English',
      year: 2010,
      contentRating: '16+',
      duration: 160,
      cover: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/el-increi-ble-hulk-1525787024.jpg?crop=1xw:1xh;center,top&resize=980:*',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
    },
    {
      id: 14,
      slug: 'tvshow-13',
      title: 'Capitán américa, Civil war',
      type: 'Drama',
      language: 'English',
      year: 2010,
      contentRating: '16+',
      duration: 160,
      cover: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/capita-n-ame-rica-civil-war-1525787826.jpg?crop=1xw:1xh;center,top&resize=980:*',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
    },
    {
      id: 15,
      slug: 'tvshow-13',
      title: 'Iron man 2',
      type: 'Drama',
      language: 'English',
      year: 2010,
      contentRating: '16+',
      duration: 160,
      cover: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/iron-man-2-1525787109.jpg?crop=1xw:1xh;center,top&resize=980:*',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
    },
    {
      id: 16,
      slug: 'tvshow-13',
      title: 'Los vengadores',
      type: 'Drama',
      language: 'English',
      year: 2010,
      contentRating: '16+',
      duration: 160,
      cover: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/vengadores-1525787643.jpg?crop=1xw:1xh;center,top&resize=980:*',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
    },
    {
      id: 17,
      slug: 'tvshow-13',
      title: 'Thor, el mundo oscuro',
      type: 'Drama',
      language: 'English',
      year: 2010,
      contentRating: '16+',
      duration: 160,
      cover: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/thor-el-mundo-oscuro-1546419545.jpg?crop=1xw:1xh;center,top&resize=980:*',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
    },
    {
      id: 18,
      slug: 'tvshow-13',
      title: 'Iron man 3',
      type: 'Drama',
      language: 'English',
      year: 2010,
      contentRating: '16+',
      duration: 160,
      cover: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/iron-man-3-1525787309.jpg?crop=1xw:1xh;center,top&resize=980:*',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
    },
    {
      id: 19,
      slug: 'tvshow-13',
      title: 'Thor',
      type: 'Drama',
      language: 'English',
      year: 2010,
      contentRating: '16+',
      duration: 160,
      cover: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/thor-1546418437.jpg?crop=1xw:1xh;center,top&resize=980:*',
      description: 'Vestibulum ac est lacinia nisi venenatis tristique',
      source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
    },
  ],
};

const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
const store = createStore(reducer, initialState, composeEnhancers());

ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById('app'),
);

